# Generated by Django 4.2.27 on 2026-01-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('IT', 'Italian'), ('GR', 'Greek'), ('MX', 'Mexican'), ('FF', 'Fast Food'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
